In [2]:
import numpy as np
a = [1, 2, 3, 4]   # 创建简单的列表
b = np.array(a)    # 将列表转换为数组
c = np.array([[1,  2],  [3,  4]]) 
print(a)
print(b)
print(c)

[1, 2, 3, 4]
[1 2 3 4]
[[1 2]
 [3 4]]


In [7]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [9]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones((1,3))

array([[1., 1., 1.]])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.randint(0, 50, 5)      	# 随机数组，5个0到50之间的数字

array([14, 33,  1, 24, 35])

In [14]:
np.random.randint(0, 50, (3,5)) 	# 3行5列，共15个随机数，都介于[0,50]

array([[25, 47, 49, 11, 19],
       [33, 11, 31, 36, 49],
       [ 1, 32, 44, 45, 42]])

In [4]:
np.random.rand(10)              	 # 10个介于[0,1)的随机数

array([0.3544838 , 0.65936662, 0.64078486, 0.20246402, 0.86962022,
       0.68874947, 0.73738167, 0.44728529, 0.55286721, 0.73098995])

In [5]:
np.random.standard_normal(5)     	 # 从标准正态分布中随机采样5个数字

array([ 1.21851314, -1.16161136, -0.377043  , -0.74208026,  1.2733149 ])

In [23]:
##修改数组中的元素值
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x[0, 2] = 4                   # 修改第0行第2列的元素值
x[1:, 1:] = 1                 # 切片，把行下标大于等于1，且列下标也大于等于1的元素值都设置1
print(x, '\n')
x[1:, 1:] = [1,2]             # 同时修改多个元素值
print(x, '\n')
x[1:, 1:] = [[1,2],[3,4]]     # 同时修改多个元素值
print(x, '\n')

[[1 2 4]
 [4 1 1]
 [7 1 1]] 

[[1 2 4]
 [4 1 2]
 [7 1 2]] 

[[1 2 4]
 [4 1 2]
 [7 3 4]] 



In [8]:
###数组与标量的运算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr, '\n')
print(1/arr, '\n')
print(arr-arr, '\n')
print(arr * arr, '\n')
print(arr ** 0.5, '\n')

[[1. 2. 3.]
 [4. 5. 6.]] 

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[ 1.  4.  9.]
 [16. 25. 36.]] 

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]] 



In [9]:
###索引和切片
arr = np.arange(10)
print(arr, '\n')
print(arr[5], '\n')
print(arr[5:8], '\n')
arr[5:8] = 12
print(arr, '\n')
arr_slice = arr[5:8]
arr_slice[1] = 12345
print(arr, '\n')
arr_slice[:] = 64
print(arr, '\n')

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d, '\n')
print(arr3d[0], '\n')
print(arr3d[0][1], '\n')

[0 1 2 3 4 5 6 7 8 9] 

5 

[5 6 7] 

[ 0  1  2  3  4 12 12 12  8  9] 

[    0     1     2     3     4    12 12345    12     8     9] 

[ 0  1  2  3  4 64 64 64  8  9] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[1 2 3]
 [4 5 6]] 

[4 5 6] 



In [14]:
###数学和统计方法
arr = np.random.randn(5, 4)  # 正态分布的数据
print(arr, '\n')
print(arr.mean(), '\n')
print(np.mean(arr), '\n')
print(arr.sum(), '\n')
print(arr.mean(axis = 1), '\n')
print(arr.sum(0), '\n')

b = np.array(arr[0])
print(arr[0])
print(b.sum())
print(b.mean())

[[-0.02134886  0.31822112 -1.25010641  0.28379751]
 [-0.22583106 -0.28652143 -1.69138703  1.85787547]
 [-0.76474621 -1.78717064  0.9088031  -0.67891217]
 [ 0.51929379 -0.26988985  0.8212208   2.29298414]
 [-0.39304449  0.36728822  0.80578667  0.54034018]] 

0.06733264215597298 

0.06733264215597298 

1.3466528431194595 

[-0.16735916 -0.08646601 -0.58050648  0.84090222  0.33009265] 

[-0.88567683 -1.65807257 -0.40568287  4.29608512] 

[-0.02134886  0.31822112 -1.25010641  0.28379751]
-0.6694366430073118
-0.16735916075182794


In [15]:
arr = np.array([[0, 1 ,2], [3, 4, 5], [6, 7, 8]])
print(arr, '\n')
print(arr.cumsum(0), '\n')
print(arr.cumprod(1), '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]] 

[[  0   0   0]
 [  3  12  60]
 [  6  42 336]] 



In [6]:
import numpy as np
x = np.array([(1,2,3,),(4,5,6)])
print(x)   #生成一个两行三列的元组
print(x.size)  
print(x.ndim)  #维度
print(x.shape)  #形状
print(x.itemsize)  #数组元素在内存中字节大小
print(x.dtype,'\n')  #类型

y = x.reshape(3,2)  #改成三行两列
print(y,'\n')
print(y.shape)


[[1 2 3]
 [4 5 6]]
6
2
(2, 3)
4
int32 

[[1 2]
 [3 4]
 [5 6]] 

(3, 2)
