# CSV文件

In [37]:
import numpy as np

In [38]:
a = np.arange(100).reshape(5,20)

In [39]:
np.savetxt('a.csv',a,fmt='%d',delimiter=',')

In [34]:
b = np.loadtxt('a.csv',delimiter=',')
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [35]:
np.savetxt('a.csv',a,fmt='%.1f',delimiter=',')

In [36]:
b = np.loadtxt('a.csv',delimiter=',')
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [25]:
b = np.loadtxt('a.csv',dtype=np.int,delimiter=',')
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

# tofile

In [40]:
a = np.arange(100).reshape(5,10,2)

In [32]:
a.tofile("a.dat",sep=',',format='%d')

In [28]:
b = np.fromfile('a.dat',dtype = np.int,sep=',')
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
b = np.fromfile('a.dat',dtype = np.int,sep=',').reshape(5,10,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

# save

In [33]:
a = np.arange(100).reshape(5,10,2)

In [34]:
np.save('a.npy',a)

In [36]:
b = np.load('a.npy')

In [37]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

# random

In [39]:
a = np.random.rand(3,4,5)
a

array([[[0.48611355, 0.83258214, 0.59421718, 0.96984484, 0.12381138],
        [0.98095845, 0.58564569, 0.75168963, 0.07345277, 0.95460641],
        [0.02114569, 0.42397834, 0.48133198, 0.30840901, 0.12072185],
        [0.5336418 , 0.60147755, 0.43200156, 0.73451102, 0.48662735]],

       [[0.93871725, 0.81321993, 0.18902638, 0.09853206, 0.16005156],
        [0.54053774, 0.90206383, 0.73592279, 0.35989213, 0.00406789],
        [0.96867682, 0.5955693 , 0.91859457, 0.2037126 , 0.608259  ],
        [0.02705169, 0.38039101, 0.53375143, 0.60760288, 0.31651388]],

       [[0.90301261, 0.26051811, 0.96587383, 0.69015682, 0.18142328],
        [0.41188836, 0.59408645, 0.12267763, 0.20258262, 0.97890336],
        [0.30654785, 0.07304638, 0.00303924, 0.9855556 , 0.38318601],
        [0.20247497, 0.8697455 , 0.03420246, 0.90198935, 0.92060663]]])

In [40]:
sn = np.random.randn(3,4,5)
sn

array([[[ 0.30791143, -0.08241097,  0.51474002, -1.77507508,
         -1.07851091],
        [-0.89672449,  0.65636593,  0.99210589, -0.91005481,
         -0.32932702],
        [-1.27958333,  0.43020909, -0.43316944, -1.13262571,
         -0.74152899],
        [-0.83267469,  1.02009133, -0.58288047,  1.07114148,
          1.22901537]],

       [[-1.06887774,  1.23162029, -0.08384934,  0.05407376,
          0.14536316],
        [-1.82379024, -0.70050698, -0.87486073, -1.4651971 ,
          0.48317089],
        [ 1.21176212,  1.50641778, -1.57664193,  0.20085473,
          0.23795822],
        [-0.85193196,  0.67083098, -0.01044794,  0.9146995 ,
         -0.42030542]],

       [[ 1.13931415,  0.5986346 ,  0.46737032, -0.58497894,
          0.79528616],
        [-0.49443534,  0.395446  , -1.1501324 ,  0.34014312,
         -0.82199927],
        [-0.24116175, -1.35289436,  0.31449672,  0.6975499 ,
          0.34738279],
        [ 1.52306061,  1.52115757, -2.68894405, -1.66035861,
          1

In [41]:
b = np.random.randint(100,200,(3,4))
b

array([[115, 142, 151, 180],
       [148, 169, 107, 195],
       [158, 101, 117, 197]])

In [42]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [44]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [46]:
a = np.random.randint(100,200,(3,4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [47]:
np.random.shuffle(a)

In [48]:
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [49]:
np.random.shuffle(a)

In [50]:
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [51]:
a = np.random.randint(100,200,(3,4))
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [59]:
np.random.permutation(a)

array([[130, 189, 112, 165],
       [131, 157, 136, 127],
       [113, 192, 186, 130]])

In [53]:
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [55]:
b = np.random.randint(100,200,(8,))

In [56]:
b

array([123, 194, 111, 128, 174, 188, 109, 115])

In [58]:
np.random.choice(b,(3,2))

array([[194, 109],
       [115, 128],
       [174, 194]])

In [60]:
np.random.choice(b,(3,2),replace=False)

array([[194, 111],
       [109, 128],
       [188, 174]])

In [63]:
np.random.choice(b,(3,2),p=b/np.sum(b))

array([[174, 194],
       [194, 128],
       [174, 111]])

# uniform,normal

In [65]:
u = np.random.uniform(0,10,(3,4))
u

array([[0.02406761, 5.48816356, 1.26971841, 0.79792681],
       [2.35038596, 6.59964947, 2.14953192, 2.03046616],
       [3.82865111, 2.24872802, 1.14648799, 5.83017052]])

In [66]:
n = np.random.normal(10,5,(3,4))
n

array([[11.60758976,  2.39530663, -0.80726459, 11.72656647],
       [14.39484692, 12.81381503, 11.44217668,  4.96759248],
       [10.2698921 ,  0.86638368,  9.54042582,  8.73408418]])

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
np.sum(a)

105

In [6]:
np.mean(a,axis=1)

array([ 2.,  7., 12.])

In [7]:
np.mean(a,axis=0)

array([5., 6., 7., 8., 9.])

In [9]:
np.average(a,axis = 0,weights=[10,5,1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [10]:
np.std(a)

4.320493798938574

In [11]:
np.var(a)

18.666666666666668

In [14]:
b = np.arange(15,0,-1).reshape(3,5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [15]:
np.max(b)

15

In [16]:
np.argmax(b)

0

In [17]:
np.unravel_index(np.argmax(b),b.shape)

(0, 0)

In [18]:
np.ptp(b)

14

In [19]:
np.median(b)

8.0

# NumPy的梯度函数

In [20]:
import numpy as np

In [24]:
a = np.random.randint(0,20,(5))
a

array([ 9,  4,  9, 15, 10])

In [25]:
np.gradient(a)

array([-5. ,  0. ,  5.5,  0.5, -5. ])

In [26]:
b = np.random.randint(0,20,(5))
b

array([ 2, 10,  3,  2, 11])

In [28]:
np.gradient(b)

array([ 8. ,  0.5, -4. ,  4. ,  9. ])

In [29]:
c = np.random.randint(0,50,(3,5))
c

array([[25,  2,  6,  3,  8],
       [47, 36, 31, 46, 23],
       [40, 18, 39, 27, 12]])

In [30]:
np.gradient(c)

[array([[ 22. ,  34. ,  25. ,  43. ,  15. ],
        [  7.5,   8. ,  16.5,  12. ,   2. ],
        [ -7. , -18. ,   8. , -19. , -11. ]]),
 array([[-23. ,  -9.5,   0.5,   1. ,   5. ],
        [-11. ,  -8. ,   5. ,  -4. , -23. ],
        [-22. ,  -0.5,   4.5, -13.5, -15. ]])]