# ndarray

In [4]:
import numpy as np

计算A^2+B^3

In [5]:
def npsum():
    a = np.array([0,1,2,3,4])
    b = np.array([9,8,7,6,5])
    
    c = a**2 + b**3
    return c
npsum()

array([729, 513, 347, 225, 141], dtype=int32)

In [6]:
a = np.array([[0,1,2,3,4],
             [9,8,7,6,5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [7]:
print(a)

[[0 1 2 3 4]
 [9 8 7 6 5]]


获得数组形状

In [9]:
a.shape

(2, 5)

获得数组维度

In [10]:
a.ndim

2

元素个数

In [11]:
a.size

10

元素类型

In [12]:
a.dtype

dtype('int32')

每个元素大小，字节为单位

In [13]:
a.itemsize

4

In [16]:
x = np.array([[0,1,2,3,4],
             [9,8,7,6]])
x

array([list([0, 1, 2, 3, 4]), list([9, 8, 7, 6])], dtype=object)

In [17]:
x.shape

(2,)

In [18]:
x.dtype

dtype('O')

In [19]:
x.itemsize

8

In [20]:
x.size

2

# ndarray数组创建

In [21]:
a = [0,1,2,3]
x = np.array(a)
print(x)

[0 1 2 3]


In [22]:
a =[[1,2],[9,8],(0,1,2)]
x = np.array(a)
print(x)

[list([1, 2]) list([9, 8]) (0, 1, 2)]


In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
np.zeros((3,6),dtype = np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [36]:
np.full((3,6),1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.ones_like(5)

array(1)

In [38]:
np.zeros_like(5)

array(0)

In [39]:
a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [40]:
b = np.linspace(1,10,4,endpoint = False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [41]:
c = np.concatenate((a,b))
c

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [42]:
a = np.ones((2,3,4),dtype = np.int32)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [43]:
a.reshape((3,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
a.resize((3,8))
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [47]:
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [51]:
b = a.flatten()

In [52]:
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [53]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [54]:
a = np.ones((2,3,4),dtype = np.int)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [55]:
a.dtype

dtype('int32')

In [57]:
b = a.astype(np.float)

In [58]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [59]:
b.dtype

dtype('float64')

In [61]:
a.dtype

dtype('int32')

In [62]:
a = np.full((2,3,4),25,dtype=np.int32)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [63]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

# 索引和切片

In [64]:
a = np.array([9,8,7,6,5])
a[2]

7

In [65]:
a[1:4:2]

array([8, 6])

In [68]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [69]:
a[1,2,3]

23

In [70]:
a[0,1,2]

6

In [71]:
a[-1,-2,-3]

17

In [73]:
a[:,1,-3]

array([ 5, 17])

In [74]:
a[:,1:3,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
a[:,:,::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

# 数组与标量之间的运算

In [77]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [78]:
a.mean()

11.5

In [80]:
a = a / a.mean()
a

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

In [81]:
np.sqrt(a)

array([[[0.        , 0.29488391, 0.41702883, 0.51075392],
        [0.58976782, 0.65938047, 0.72231512, 0.7801895 ],
        [0.83405766, 0.88465174, 0.93250481, 0.97801929]],

       [[1.02150784, 1.06321907, 1.10335457, 1.14208048],
        [1.17953565, 1.21583752, 1.25108648, 1.28536917],
        [1.31876095, 1.35132785, 1.38312815, 1.41421356]]])

In [82]:
np.cos(a)

array([[[ 1.        ,  0.99622166,  0.98491521,  0.96616606],
        [ 0.94011592,  0.90696163,  0.86695373,  0.82039454],
        [ 0.7676359 ,  0.70907648,  0.6451588 ,  0.57636587]],

       [[ 0.50321753,  0.42626654,  0.3460944 ,  0.26330693],
        [ 0.17852974,  0.09240345,  0.00557891, -0.0812878 ],
        [-0.16754024, -0.25252663, -0.33560476, -0.41614684]]])

In [83]:
np.tan(a)

array([[[ 0.00000000e+00,  8.71763588e-02,  1.75687896e-01,
          2.66952860e-01],
        [ 3.62566867e-01,  4.64422343e-01,  5.74873399e-01,
          6.96979124e-01],
        [ 8.34883063e-01,  9.94436569e-01,  1.18427975e+00,
          1.41783510e+00]],

       [[ 1.71726880e+00,  2.12214076e+00,  2.71082022e+00,
          3.66383108e+00],
        [ 5.51132003e+00,  1.07758056e+01,  1.79243805e+02,
         -1.22612581e+01],
        [-5.88434907e+00, -3.83163529e+00, -2.80688178e+00,
         -2.18503986e+00]]])

In [84]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [89]:
a = np.sqrt(a)
a

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [90]:
np.modf(a)

(array([[[0.        , 0.        , 0.41421356, 0.73205081],
         [0.        , 0.23606798, 0.44948974, 0.64575131],
         [0.82842712, 0.        , 0.16227766, 0.31662479]],
 
        [[0.46410162, 0.60555128, 0.74165739, 0.87298335],
         [0.        , 0.12310563, 0.24264069, 0.35889894],
         [0.47213595, 0.58257569, 0.69041576, 0.79583152]]]),
 array([[[0., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 3., 3., 3.]],
 
        [[3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]]))

In [91]:
np.maximum(a,b)

array([[[1.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [92]:
a > b

array([[[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])