pandas导入

In [9]:
import pandas as pd
import numpy as np

Series创建

In [10]:
# 使用python数组创建
pd.Series([11, 12], index=["北京", "上海"])

北京    11
上海    12
dtype: int64

In [11]:
# 使用numpy数组创建
pd.Series(np.arange(3,6))

0    3
1    4
2    5
dtype: int32

In [12]:
# 使用python字典创建
pd.Series({"北京": 11, "上海": 12, "深圳": 14})

北京    11
上海    12
深圳    14
dtype: int64

In [14]:
obj = pd.Series([4,7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

Series values和index属性

In [16]:
obj = pd.Series([4, 7, -5, 3])
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [17]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
obj[2]

-5

In [19]:
obj[1] = 8
obj[[0,1, 3]]

0    4
1    8
3    3
dtype: int64

In [22]:
obj2 =pd.Series([4,2,-5, 3 ],index=['a','b','c','d'])
obj2

a    4
b    2
c   -5
d    3
dtype: int64

In [23]:
obj2['a']

4

In [24]:
obj2['d'] = 6
obj2

a    4
b    2
c   -5
d    6
dtype: int64

In [26]:
obj2[['a','b','d']]

a    4
b    2
d    6
dtype: int64

Series中最重要的一个功能是：它会在算术运算中自动对齐不同索引的数据

In [30]:
obj2 = pd.Series({"Ohio": 35000, "Oregon": 16000, "Texas": 71000, "Utah": 5000})
obj3 = pd.Series({"California": np.nan, "Ohio": 35000, "Oregon": 16000, "Texas": 71000})
print(obj2,'\n')
print(obj3,'\n')
print(obj2 + obj3, '\n')

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64 

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64 

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64 



In [31]:
# name属性
obj3.name= 'population'
obj3.index.name = 'state'
print(obj3,'\n')

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64 



In [32]:
# 修改Series索引
obj = pd.Series([4, 7, -5, 3])
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj)

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


DataFrame

In [34]:
# 创建一个空的DataFrame
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [36]:
# 由单列表创建DataFrame
data = [1,2,3,4]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4


In [37]:
# 由嵌套列表创建DataFrame,并指定数据类型
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


In [38]:
# 由数组组成的字典创建DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000
, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9


In [41]:
# 指定列的顺序
frame = pd.DataFrame(data, columns=['year', 'state', 'pop'])
print(frame)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9


In [43]:
# 传入值中无对应列，刚产生NaN值
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN


In [44]:
# 将DataFrame获取为一个列表
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [45]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [46]:
# 修改列的值 
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [51]:
frame2['debt'] = np.arange(5.0)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [52]:
# 指定索引修改列的值，使用Series精确匹配DataFrame索引，空位由缺省值填充
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [53]:
# 为不存在的列赋值会创建新的列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [54]:
# del删除列
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [62]:
# 嵌套字典创建DataFrame
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [63]:
# 转置
# print(frame3.T)

In [64]:
# 设定DataFrame Index和columns的name属性
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [65]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [66]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)