In [1]:
import numpy.matlib 
import numpy as np
 
print (np.matlib.empty((2,2)))
# 填充为随机数据

[[1.67494829e+243 5.82477780e+252]
 [2.02910187e+174 2.46052273e-154]]


In [2]:
import numpy.matlib 
import numpy as np 
 
print (np.matlib.zeros((2,2)))
print (np.matlib.ones((2,2)))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [3]:
import numpy.matlib 
import numpy as np 
 
print (np.matlib.eye(n =  3, M =  4, k =  0, dtype =  int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [4]:
import numpy.matlib 
import numpy as np 
 
# 大小为4，类型为整型
print (np.matlib.identity(4, dtype = int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [2]:
import numpy.matlib 
import numpy as np 
 
print (np.matlib.rand(4,4))

[[0.60816204 0.96497772 0.99442573 0.16514713]
 [0.36112951 0.5849557  0.17710848 0.25984388]
 [0.39050801 0.12108994 0.73987486 0.54932934]
 [0.87680497 0.74928449 0.1441885  0.20470777]]


In [3]:
import numpy.matlib 
import numpy as np  
 
i = np.matrix('1,2;3,4')  
print(i)
j = np.asarray(i)
print(j)
k = np.asmatrix (j)  
print (k)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6]])
y = np.matrix([1,2,3,4,5,6])
print(x.T, y.T, sep='\n\n')

[[1 4]
 [2 5]
 [3 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6],[7,8,9]])
print(x.mean(), end='\n====\n')             # 所有元素平均值
print(x.mean(axis=0), end='\n====\n')       # 纵向平均值
print(x.mean(axis=0).shape, end='\n====\n')
print(x.mean(axis=1), end='\n====\n')       # 横向平均值
print(x.sum(), end='\n====\n')              # 所有元素之和
print(x.max(axis=1), end='\n====\n')        # 横向最大值
print(x.argmax(axis=1), end='\n====\n')     # 横向最大值的下标
print(x.diagonal(), end='\n====\n')         # 对角线元素

5.0
====
[[4. 5. 6.]]
====
(1, 3)
====
[[2.]
 [5.]
 [8.]]
====
45
====
[[3]
 [6]
 [9]]
====
[[2]
 [2]
 [2]]
====
[[1 5 9]]
====


In [8]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6]])
y = np.matrix([[1,2], [3,4], [5,6]])
print(x*y)

[[22 28]
 [49 64]]


In [11]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6], [7,8,0]])
y = np.linalg.inv(x)
print(y)
print(x*y)          # 对角线元素为1，其他元素为0或近似为0
print(y*x)

[[-1.77777778  0.88888889 -0.11111111]
 [ 1.55555556 -0.77777778  0.22222222]
 [-0.11111111  0.22222222 -0.11111111]]
[[ 1.00000000e+00  1.66533454e-16  1.38777878e-17]
 [-1.05471187e-15  1.00000000e+00  2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00 -4.44089210e-16  0.00000000e+00]
 [ 2.77555756e-16  1.00000000e+00  0.00000000e+00]
 [ 6.93889390e-17  1.11022302e-16  1.00000000e+00]]


In [12]:
import numpy.matlib
import numpy as np
 
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))

[[37 40]
 [85 92]]


In [13]:
import numpy as np 
 
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积
print (np.vdot(a,b))

130


In [14]:
import numpy as np 
 
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y)
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [16]:
import numpy as np

a = np.array([[1,1,1], [0,2,5],[2,5,-1]])   # 系数矩阵
b = np.array([6,-4,27])            # 系数矩阵
x = np.linalg.solve(a, b)      # 求解
print(x)
print(np.dot(a, x))            # 验证

[ 5.  3. -2.]
[ 6. -4. 27.]
